# Generated by Django 5.1.4 on 2024-12-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bankupload',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('acc_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('amount', models.FloatField()),
                ('bank_type', models.CharField(choices=[('one', 'saving account'), ('two', 'current account')], max_length=15)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trans_detail',
            fields=[
                ('acc_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('amount_added', models.FloatField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
