# Generated by Django 5.1.4 on 2024-12-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trans_detail',
        ),
        migrations.AlterField(
            model_name='bankupload',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
