# Generated by Django 5.1.4 on 2024-12-11 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0003_bankupload_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankupload',
            name='user',
        ),
    ]
