# Generated by Django 5.1.4 on 2024-12-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0022_alter_addamount_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='addamount',
            name='acc_no',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
