# Generated by Django 5.1.4 on 2024-12-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0023_addamount_acc_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addamount',
            name='acc_no',
        ),
        migrations.AlterField(
            model_name='addamount',
            name='account_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
