# Generated by Django 5.1.4 on 2024-12-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0024_remove_addamount_acc_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addamount',
            name='id',
        ),
        migrations.AlterField(
            model_name='addamount',
            name='account_number',
            field=models.CharField(default=0, max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
