# Generated by Django 5.1.4 on 2024-12-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0028_addamount_id_bankupload_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankupload',
            name='id',
        ),
        migrations.AlterField(
            model_name='bankupload',
            name='acc_no',
            field=models.CharField(default=0, max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
