# Generated by Django 5.1.4 on 2024-12-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0033_bankupload_id_alter_bankupload_acc_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addamount',
            name='id',
        ),
        migrations.RemoveField(
            model_name='bankupload',
            name='id',
        ),
        migrations.AlterField(
            model_name='addamount',
            name='account_number',
            field=models.CharField(default=0, max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankupload',
            name='acc_no',
            field=models.CharField(default=0, max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
