# Generated by Django 5.1.4 on 2024-12-17 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0034_remove_addamount_id_remove_bankupload_id_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='addamount',
        #     name='',
        #     field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='PK'),
        #     preserve_default=False,
        # ),
        migrations.AlterField(
            model_name='addamount',
            name='account_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bankapp.bankupload'),
        ),
    ]
