# Generated by Django 5.1.4 on 2024-12-18 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0038_addamount_id_alter_addamount_account_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='addamount',
            name='amount_added',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='CreditPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(max_length=10, null=True)),
                ('bill_payments', models.CharField(choices=[('one', 'mobile recharge'), ('two', 'DTH/Cable TV'), ('three', 'Electricity'), ('four', 'Subscription fee'), ('five', 'Loan EMI')], max_length=15)),
                ('creditpay_amount', models.FloatField(default=0, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DebitPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(max_length=10, null=True)),
                ('bill_payments', models.CharField(choices=[('one', 'mobile recharge'), ('two', 'DTH/Cable TV'), ('three', 'Electricity'), ('four', 'Subscription fee'), ('five', 'Loan EMI')], max_length=15)),
                ('debitpay_amount', models.FloatField(default=0, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
