# Generated by Django 5.1.4 on 2024-12-18 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0039_alter_addamount_amount_added_creditpayment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditpayment',
            name='account_no',
        ),
        migrations.RemoveField(
            model_name='debitpayment',
            name='account_no',
        ),
    ]
