# Generated by Django 5.1.4 on 2024-12-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0040_remove_creditpayment_account_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankupload',
            name='loan',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
