# Generated by Django 5.1.4 on 2024-12-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0041_bankupload_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpayment',
            name='bill_payments',
            field=models.CharField(choices=[('one', 'mobile recharge'), ('two', 'DTH/Cable TV'), ('three', 'Electricity'), ('four', 'Subscription fee'), ('five', 'Water')], max_length=15),
        ),
        migrations.AlterField(
            model_name='debitpayment',
            name='bill_payments',
            field=models.CharField(choices=[('one', 'mobile recharge'), ('two', 'DTH/Cable TV'), ('three', 'Electricity'), ('four', 'Subscription fee'), ('five', 'Water')], max_length=15),
        ),
    ]
