# Generated by Django 5.1.4 on 2024-12-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0042_alter_creditpayment_bill_payments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitpayment',
            name='bill_payments',
            field=models.CharField(choices=[('one', 'mobile recharge'), ('two', 'DTH/Cable TV'), ('three', 'Electricity'), ('four', 'Subscription fee'), ('five', 'Water'), ('six', 'Loan Re-Payment')], max_length=15),
        ),
    ]
