# Generated by Django 5.1.4 on 2024-12-19 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0043_alter_debitpayment_bill_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addamount',
            name='account_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bankapp.bankupload'),
        ),
    ]
