# Generated by Django 5.1.4 on 2025-01-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0044_alter_addamount_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankupload',
            name='bank_type',
            field=models.CharField(choices=[('saving account', 'saving account'), ('current account', 'current account')], max_length=15),
        ),
        migrations.AlterField(
            model_name='creditpayment',
            name='bill_payments',
            field=models.CharField(choices=[('mobile recharge', 'mobile recharge'), ('DTH/Cable TV', 'DTH/Cable TV'), ('Electricity', 'Electricity'), ('Subs fee', 'Subs fee'), ('Water', 'Water')], max_length=15),
        ),
        migrations.AlterField(
            model_name='debitpayment',
            name='bill_payments',
            field=models.CharField(choices=[('mobile recharge', 'mobile recharge'), ('DTH/Cable TV', 'DTH/Cable TV'), ('Electricity', 'Electricity'), ('Subs fee', 'Subs fee'), ('Water', 'Water'), ('Loan Re-Payment', 'Loan Re-Payment')], max_length=15),
        ),
    ]
